#Kafka Configuration

spring.kafka.bootstrap-servers=localhost:9092

#Redis Configuration

spring.data.redis.host=localhost
spring.data.redis.port=6379

#JPA Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true